name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps: # para usar action eu uso o -uses e para rodar comandos eu uso o -run
      - uses: actions/checkout@v2 # essa action pega os dados do que eu acabei de subir e vai baixar nessa máquina ubuntu
      - uses: actions/setup-go@v2 # essa action vai instalar o go no meu ambiente
        with:
          go-version: 1.15 # qual a versão do go que eu quero instalar
      - run: go test
      - run: go run math.go